Repository Music-Bot-for-Jitsi/Jimmi, pull requests merged in 2022-03, with the labels that each got.

#109 Disable renaming of index.ts to mod.ts
  .github/workflows/update-api-client.yml
Labels: enhancement

#127 Fix/cd pipelines
  .dockerignore
  .github/workflows/cd-container-backend.yml
  .github/workflows/cd-container-frontend.yml
  backend/Dockerfile
  docker-compose.build.yml
  frontend/Dockerfile
  frontend/public/global.css
  frontend/public/index.html
Labels: fix, automation

#138 Added missing environment export
  backend/src/configuration/environment.ts
Labels: bug
