Repository Music-Bot-for-Jitsi/Jimmi, pull requests merged in 2022-04, with the labels that each got.

#140 Updated quickstart and architecture
  docs/ARCHITECTURE.md
  docs/QUICKSTART.md
Labels: documentation

#142 Fixed release pipeline
  .github/workflows/cd-binaries.yml
Labels: bug

#144 add snel to workflow
  .github/workflows/cd-binaries.yml
Labels: fix, automation
